### ISSUE TITLE
Change all out of line x64 assembly code to use rustc's inline assembler via global_asm! and include_str!

### ISSUE THREAD

**Issue by mdpcs3544** [CharlotteOS-Deprecated/charlotte-core#100]
To do this you will need to:

- [x] change all assembler directives from NASM to GCC directives in the assembly code
- [x] Use global_asm! and include_str! as well as extern "C" declarations to pull in assembly functions
- [x] Remove the part of the cargo build script that calls out to NASM
- [x] Remove NASM from being installed by the install scripts
- [x] Remove all references to NASM in all documentation and readme files across the organization

**Comment by Wrench56** [comment]
What is the status of this issue? I do believe the code doesn't have any NASM reference anymore. Can we mark this resolved?

**Comment by Wrench56** [comment]
Closing issue, as no repositories reference NASM anymore.
