### ISSUE TITLE
[Refactor] Change `arch` to use a single trait that encapsulates all of the information needed by the kernel to interact with target systems' instruction set architectures

### ISSUE THREAD

**Issue by mdpcs3544** [CharlotteOS-Deprecated/charlotte-core#131]

**Comment by mdpatelcsecon** [comment]
I've decided to split arch into separate per subsystem `isa` submodules to allow for more flexibility. This breaks with the usual layered vertical kernel architecture and instead adopts a horizontal one with modularity expressed on a per subsystem basis as opposed to the usual per abstraction layer basis. I figure this will make maintenance of the code base easier in the long run.

**Comment by mdpcs3544** [comment]
I've decided to split arch into separate per subsystem isa submodules to allow for more flexibility. This breaks with the usual layered vertical kernel architecture and instead adopts a horizontal one with modularity expressed on a per subsystem basis as opposed to the usual per abstraction layer basis. I figure this will make maintenance of the code base easier in the long run.
