### ISSUE TITLE
Discord Link Broken on Homepage

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [CharlotteOS-Deprecated/charlotte-core#133]
The discord link on the [Homepage](https://github.com/charlotte-os) seems to be invalid.

**Comment by mdpatelcsecon** [comment]
It should work now. 

Also please make an issue on the correct repository going forward as this is the kernel and not the organization description one or alternatively feel free to send us an email at charlotte-os@outlook.com.

**Comment by mdpcs3544** [comment]
It should work now.

Also please make an issue on the correct repository going forward as this is the kernel and not the organization description one or alternatively feel free to send us an email at [charlotte-os@outlook.com](mailto:charlotte-os@outlook.com).
