### ISSUE TITLE
Pull in zenalloc and implement its high level memory allocation traits

### ISSUE THREAD

**Issue by mdpcs3544** [CharlotteOS-Deprecated/charlotte-core#14]
Pull in and implement our `zenalloc` crate in the kernel to provide an interface that the kernel can use for its own dynamic memory needs as well as to implement any memory related system calls for userspace. 

Prerequisites: #58 and #11

**Comment by xadaemon** [comment]
Prerequisite #9 is done.

Prerequisite remaining is #11,
Required by: #25

**Comment by xadaemon** [comment]
should bring a proposal to solve this one in the next few days

**Comment by mdpcs3544** [comment]
This issue is blocked on the PMM and VMM work being completed.

**Comment by mdpcs3544** [comment]
zenalloc has been deleted since we do not want to spend time developing parts of it that we do not need. Any dynamic structures to be used in the kernel will live in the kernel codebase.
