### ISSUE TITLE
Add rustdoc comments and doc macros to all existing code files

### ISSUE THREAD

**Issue by mdpcs3544** [CharlotteOS-Deprecated/charlotte-core#16]
Add documentation comments and doc macros to all existing code files so documentation can be automatically generated from the source code using rustdoc.

**Comment by ibaryshnikov** [comment]
What is `Api` trait in `arch/mod.rs`?

**Comment by mdpcs3544** [comment]
@ibaryshnikov That is the common interface used by the rest of the kernel to interact with ISA specific code.

**Comment by mdpcs3544** [comment]
@ibaryshnikov I added some doc comments myself and pushed them to main. You should rebase your branch on the latest main branch to get the changes.

**Comment by mdpcs3544** [comment]
This issue is open for anyone to grab and it should be relatively easy albeit maybe tedious.

**Comment by Wrench56** [comment]
After the recent devops update, we should also add `Security` comments explaining `unsafe` blocks.

**Comment by mdpcs3544** [comment]
I strongly agree. Unsafe in Rust means that there is one or more invariants that the compiler cannot automatically check and the developer needs to manually ensure are upheld. We should have comments explaining what those are on unsafe functions and traits and when unsafe things are used have a comment explaining how the required invariants are guaranteed to be upheld.

**Comment by mdpcs3544** [comment]
This is no longer needed as of the restart.
