### ISSUE TITLE
Add ISRs for all of the x86-64 CPU exceptions

### ISSUE THREAD

**Issue by mdpcs3544** [CharlotteOS-Deprecated/charlotte-core#20]
Add an interrupt service routine for each CPU excpetion that at minimum logs that the exception occurred and if possible handles it and returns to the interrupted code using the `iretq` instruction.

All registers must be preserved across any exception that can be recovered from. The registers should be pushed onto the stack instead of an array in the BSS section to allow for interrupts to occur while an ISR is already running.

**Comment by parkerstafford** [comment]
Working
