### ISSUE TITLE
Terminal Interface

### ISSUE THREAD

**Issue by EthanPlant** [CharlotteOS-Deprecated/charlotte-core#28]
Implement a TTY interface for easily logging text to the screen:
- The TTY interface should implement the rust `write!` and `writeln!` macros for formatted output.
- Potentially, it should implement the `print!` and `println!` rust macros
- It should support scrolling the text when the end of the screen is reached
- It should be able to handle all 127 ASCII characters, including control characters like `\n`, `\t`, and `\r`.

**Comment by mdpcs3544** [comment]
@EthanPlant Does merging #33 close this issue?

**Comment by EthanPlant** [comment]
Yes it does. Forgot to attach the PR.
