### ISSUE TITLE
[tracking] Building on aarch64-unknown-none

### ISSUE THREAD

**Issue by xadaemon** [CharlotteOS-Deprecated/charlotte-core#48]
This issue is intended to track progress on allowing the kernel to build for `aarch64-unknown-none`.

Blockers:
TODO: list here the blockers.

**Comment by EthanPlant** [comment]
#75 is a start to this.

**Comment by mdpcs3544** [comment]
This being shelved as we have agreed to develop exclusively for x64 until reaching a MVP or the community decides otherwise.
