### ISSUE TITLE
Improve framebuffer color support 

### ISSUE THREAD

**Issue by EthanPlant** [CharlotteOS-Deprecated/charlotte-core#52]
While the framebuffer in theory supports every possible ARGB color, in practice right now it's fairly difficult to do so.

Ideally some common predefined colours (such as black, red, green, etc.) should be defined as constants (likely a `Color` enum), so instead of having to pass something like `0xFFFF00FF`, they could pass `Color::MAGENTA`.

It would also be neat to modify the console to allow setting a foreground and background color to make writing colored text easier. Adding support for inline colored text to the print and println macros could be neat but this would likely be complex.

**Comment by mdpatelcsecon** [comment]
Closed by #70

**Comment by mdpcs3544** [comment]
Closed by #70
