### ISSUE TITLE
[tracking] Physical frame allocator has extremely poor performance

### ISSUE THREAD

**Issue by EthanPlant** [CharlotteOS-Deprecated/charlotte-core#53]
The physical frame allocator currently is currently extremely slow to allocate and deallocate frames, as memory allocation is incredibly critical this needs to be optimised. Creating a tracking issue for this.

**Comment by mdpcs3544** [comment]
We should strongly consider reimplementing this from scratch.

**Comment by mdpcs3544** [comment]
Closed by #54
