### ISSUE TITLE
[tracking] Parse static ACPI tables

### ISSUE THREAD

**Issue by EthanPlant** [CharlotteOS-Deprecated/charlotte-core#55]
Tracking issue for parsing the static ACPI tables.

- [x]  Request RDSP info from Limine
- [x] RSDP
- [x] BGRT
- [x] FADT
- [x] MADT (In progress)
- [x] RSDT
- [x] XSDT
- [x] SRAT

**Comment by xadaemon** [comment]
Madt and SRAT were completed, so this can be closed
