### ISSUE TITLE
Improve Logger

### ISSUE THREAD

**Issue by parkerstafford** [CharlotteOS-Deprecated/charlotte-core#87]
- Improve the logger with multiple log levels

**Comment by Wrench56** [comment]
Just for the record: The branch `improve-logger` includes a draft of the new logging system. It is closer to being a driver/module healthcheck system visually. To finish it, we still need memory allocation (String and format!() are both needed). With that being said the other branch `logger-loglevels` is an upgrade compared to the previous logger as it includes log levels.

**Comment by ThatOSDeveloper** [comment]
logger-loglevels has been implemented and pushed to the main branch, this feature is now finished.
